spring:
  application:
    name: eureka2
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8763/eureka3/
    register-with-eureka: false
server:
  port: 8762
